import Header from "@/src/components/templates/layout/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Header />
        {/* 반응형 사이즈 지정 */}
        <main
          className={`w-full sm:max-w-screen-sm md:max-w-screen-md lg:max-w-screen-lg mx-auto`}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
