import { IGetRecruit } from "@/src/type/recruit.interface";

export const RECRUIT_POST_LIST: IGetRecruit[] = [
  {
    id: "1",
    title: "Data1 모집",
    partId: "data",
    partLabel: "Data",
    careerType: "career",
    workType: "regular",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Data2 모집",
    partId: "data",
    partLabel: "Data",
    careerType: "newbie",
    workType: "regular",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "FE1 모집",
    partId: "frontend",
    partLabel: "Frontend",
    careerType: "newbie",
    workType: "intern",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "FE2 모집",
    partId: "frontend",
    partLabel: "Frontend",
    careerType: "all",
    workType: "contract",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "5",
    title: "BE 모집",
    partId: "backend",
    partLabel: "Backend",
    careerType: "all",
    workType: "regular",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    title: "Marketing 모집",
    partId: "marketing",
    partLabel: "Marketing",
    careerType: "career",
    workType: "regular",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
